# Generated by Django 4.1.2 on 2022-10-31 15:51

import backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Farm Name', max_length=200)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('stripe_account_id', models.CharField(blank=True, max_length=1000)),
                ('is_registered', models.BooleanField(default=False)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='FarmBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_farmer', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_notifiable', models.BooleanField(default=False)),
                ('primary_phone', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('farm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.farm')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', backend.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FarmVegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_weight', models.CharField(default='lb', max_length=5)),
                ('max_order_amount', models.DecimalField(decimal_places=2, default=99999, max_digits=8)),
                ('available_amount', models.DecimalField(decimal_places=2, default=99999, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('farm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.farmboy')),
            ],
        ),
        migrations.CreateModel(
            name='FarmVegetableOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('order_amount', models.DecimalField(decimal_places=2, default=99999, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('farm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.farm')),
                ('farm_vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.farmvegetable')),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('cron_string', models.CharField(max_length=100)),
                ('end_cron_string', models.CharField(max_length=100)),
                ('market_duration_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('market_pickup_date', models.DateTimeField(null=True)),
                ('amount', models.PositiveIntegerField()),
                ('fee', models.PositiveIntegerField()),
                ('stripe_checkout_session_id', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='backend.farmboy')),
                ('farm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.farm')),
                ('farm_vegetables', models.ManyToManyField(to='backend.farmvegetableorder')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to='backend.farmboy')),
                ('market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.market')),
            ],
            managers=[
                ('custom_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MarketInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_string', models.CharField(max_length=100)),
                ('end_cron_string', models.CharField(max_length=100)),
                ('market_duration_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.farm')),
                ('farm_vegetables', models.ManyToManyField(to='backend.farmvegetable')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.market')),
            ],
        ),
    ]
