# Generated by Django 4.1.2 on 2022-11-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_market_farms'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='created',
            field=models.DateTimeField(auto_now=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='created_by',
            field=models.CharField(default='farmer@test.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='updated_by',
            field=models.CharField(default='farmer@test.com', max_length=50),
            preserve_default=False,
        ),
    ]
