# Generated by Django 4.1.2 on 2022-11-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_farm_created_farm_created_by_farm_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
