# Generated by Django 4.1.2 on 2022-11-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_market_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='market',
        ),
        migrations.AddField(
            model_name='order',
            name='market_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.marketinfo'),
        ),
    ]
